In [1]:
a ='foo'
a.capitalize

<function str.capitalize()>

In [2]:
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))

%time for _ in range(10): my_arr = my_arr * 2

%time for _ in range(10): my_list = my_list * 2


Wall time: 24.9 ms
Wall time: 1min


In [3]:
data = np.random.randn(2,3) #生成一个2*3的多维数组每个值符合的是标准正态分布
data * 10
data.shape
data.dtype


dtype('float64')

In [4]:
data1 = [6, 7.5, 8, 0 ,1]
arr1 = np.array(data1) #将列表改为一维array
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [5]:
data2 = [[1,2,3,4],[5,6,7,8]] #由于列表里有两个列表，因此自动生成二维数组
arr2 = np.array(data2)
arr2.ndim 
arr2.shape

(2, 4)

In [7]:
np.zeros(10)# 创建1行十列的二维数组
arr3 = np.zeros((3,6))#创建3行6列的二维数组
arr4 = np.empty((2,3,2))#三维数组，该多维数组里面有2个 2*3的数组
arr4.ndim

3

In [8]:
np.arange(15) #包含起点但不包含终点


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
arr5 = np.array([1, 2, 3, 4, 5])
arr5.dtype
float_arr5 = arr5.astype(np.float64)
float_arr5.dtype

dtype('float64')

In [13]:
import numpy as np
arr6 = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr6 = arr6.astype(np.int32)  #得加上arr6


In [14]:
pip install --upgrade numpy

Requirement already up-to-date: numpy in c:\users\90512\anaconda3\lib\site-packages (1.18.1)
Note: you may need to restart the kernel to use updated packages.


In [15]:
int_array = np.arange(10)
print(int_array.dtype)
calibers = np.array([.22, .270, .357, .38, .44, .50], dtype = np.float64)
int_array.astype(calibers.dtype)

int32


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [16]:
empty_unit32 = np.empty(8, dtype = 'u4')
empty_unit32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [18]:
arr2 = np.array([[1., 2., 3.],[4., 5., 6.]])
arr2 * arr2
1/arr2
arr2 * 5

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [20]:
arr = np.arange(10)
arr[5]
arr[5:8]
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [22]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [23]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [25]:
arr_slice[:] = 64
arr

array([64, 64, 64, 64, 64, 64, 64, 64, 64, 64])

In [28]:
arr_copy = arr[5:8].copy()
arr_copy

array([64, 64, 64])

In [31]:
arr2d = np.array([[1,2,3],[4, 5, 6],[7,8,9]])
arr2d[2]
arr2d[0][2]
arr2d[0,2]

3

In [53]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [48]:
arr3d[0]

array([[42, 42, 42],
       [42, 42, 42]])

In [62]:
old_values = arr3d[0].copy()
arr3d[0] = 42

old_values

array([[42, 42, 42],
       [42, 42, 42]])