In [1]:
a ='foo'
a.capitalize

<function str.capitalize()>

In [4]:
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))

%time for _ in range(10): my_arr = my_arr * 2

%time for _ in range(10): my_list = my_list * 2


Wall time: 29.9 ms
Wall time: 1min 13s


In [13]:
data = np.random.randn(2,3) #生成一个2*3的多维数组每个值符合的是标准正态分布
data * 10
data.shape
data.dtype


dtype('float64')

In [19]:
data1 = [6, 7.5, 8, 0 ,1]
arr1 = np.array(data1) #将列表改为一维array
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [24]:
data2 = [[1,2,3,4],[5,6,7,8]] #由于列表里有两个列表，因此自动生成二维数组
arr2 = np.array(data2)
arr2.ndim 
arr2.shape

(2, 4)

In [33]:
np.zeros(10)# 创建1行十列的二维数组
arr3 = np.zeros((3,6))#创建3行6列的二维数组
arr4 = np.empty((2,3,2))三维数组，该多维数组里面有2个 2*3的数组
arr4.ndim

3

In [36]:
np.arange(15) #包含起点但不包含终点


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [41]:
arr5 = np.array([1, 2, 3, 4, 5])
arr5.dtype
float_arr5 = arr.astype(np.float64)
float_arr5.dtype

dtype('float64')

In [9]:
import numpy as np
arr6 = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr6 = arr6.astype(np.int32)  #得加上arr6


array([ 3, -1, -2,  0, 12, 10])

In [1]:
pip install --upgrade numpy

Requirement already up-to-date: numpy in c:\users\90512\anaconda3\lib\site-packages (1.18.1)
Note: you may need to restart the kernel to use updated packages.


In [12]:
int_array = np.arange(10)
print(int_array.dtype)
calibers = np.array([.22, .270, .357, .38, .44, .50], dtype = np.float64)
int_array.astype(calibers.dtype)

int32


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [15]:
empty_unit32 = np.empty(8, dtype = 'u4')
empty_unit32

array([1671073048,        540,       1052,          0,        976,
                0,        976,          0], dtype=uint32)

In [20]:
arr2 = np.array([[1., 2., 3.],[4., 5., 6.]])
arr2 * arr2
1/arr
arr2 * 5

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [21]:
arr2 > arr

array([[False, False, False],
       [False, False, False]])

In [28]:
arr = np.arange(10)
arr[5]
arr[5:8]
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])